### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by tgriesser** [prisma/nexus#1]
Just adding a list of things I come across as I work on this with a real-world api

Todo:
- [x] Multi-dimensional arrays (and nullability?)
- [ ] Option to strip unused (inaccessible) types from schema gen / type gen
- [x] ~~Check for undefined on args, for accidentally mixing `.field` w/ `.fieldArg`~~ edit: removed `fieldArg`
- [x] `required: true` on input arg members
- [ ] Example of wrapping type for connections (gqliteral-contrib)
- [x] Configuring nullability on type level
- [ ] ~~Option to use existing typegen for arg types?~~
- [x] Sensible defaults for return types without root
- [x] Check if lexicographicSortSchema is a function before calling (older graphql)
- [ ] Check for empty types (no fields, members, etc.) before typegen
- [ ] ~~Toggle for pre-TS3.0 features?~~
- [x] Type completion/validation for `backingTypes`
- [x] Re-export types from gqliteral
- [x] Validate name
- [x] Explicit toggle for whether to run `fs` things
- [ ] Tests for all of the features

Ideas / Maybe Todo:
- [ ] Validation on field level / type level? Or at least ability to wrap for plugins
- [ ] ~~Plugin API, e.g. adding custom fields for type building: `t.date` / `t.dateArg`~~ (encouraging wrapping) 

Other things:
- [ ] Subscriptions

**Comment by tgriesser** [comment]
Now that this is "released", going to close this. We can split out new features into individual tickets.
